import {useCallback,useEffect,useState} from 'react';
import {CalendarDays,Users,ClipboardList,Building2,ArrowRight,ChevronRight,Check,RefreshCw,Search,ExternalLink,Copy,Heart,ShieldCheck,UserMinus} from 'lucide-react';
import {api,ApiError,dateLabel,timeRange} from './api';
import {ActivityList,ApprovalNote,Avatar,Dialog,ShiftDetails,Status} from './components';
import VolunteerPage from './VolunteerPage';
import type {Workspace,Shift,Candidates,Invitation,Preparation} from './types';

type View='coverage'|'volunteers'|'activity';

export default function App(){
 const match=location.pathname.match(/^\/invite\/([^/]+)$/);
 return match?<VolunteerPage token={decodeURIComponent(match[1])}/>:<Coordinator/>;
}

function Coordinator(){
 const [restartSample,setRestartSample]=useState(false);
 const [needsLogin,setNeedsLogin]=useState(false),[accessCode,setAccessCode]=useState('');
 const [workspace,setWorkspace]=useState<Workspace|null>(null),[view,setView]=useState<View>('coverage'),[selected,setSelected]=useState('s1');
 const [candidates,setCandidates]=useState<Candidates|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[notice,setNotice]=useState('');
 const [mode,setMode]=useState<'rules'|'bedrock'>('rules'),[review,setReview]=useState<Invitation|null>(null),[message,setMessage]=useState('');
 const [result,setResult]=useState<Preparation|null>(null),[search,setSearch]=useState(''),[cancel,setCancel]=useState<{shift:Shift;id:string;name:string}|null>(null);
 const reload=useCallback(async()=>{const data=await api<Workspace>('/workspace');setWorkspace(data);return data;},[]);
 useEffect(()=>{let active=true;api('/session',{}).then(()=>api<Workspace>('/workspace')).then(data=>{if(active)setWorkspace(data);}).catch(e=>{if(active){if(e instanceof ApiError&&e.status===401)setNeedsLogin(true);else setError(e.message);}});return()=>{active=false;};},[]);
 useEffect(()=>{if(!workspace)return;const interval=setInterval(()=>void reload().catch(()=>{}),10000);return()=>clearInterval(interval);},[!!workspace,reload]);
 useEffect(()=>{if(!workspace)return;let active=true;api<Candidates>(`/shifts/${selected}/candidates`).then(data=>{if(active)setCandidates(data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[selected,workspace]);
 const run=async(label:string,task:()=>Promise<void>)=>{setBusy(label);setError('');setNotice('');try{await task();}catch(e){setError((e as Error).message);if(e instanceof ApiError&&e.status===401){setWorkspace(null);setNeedsLogin(true);}}finally{setBusy('');}};
 const choose=(id:string)=>{setSelected(id);setCandidates(null);setResult(null);};
 const openReview=(inv:Invitation)=>{setReview(inv);setMessage(inv.message);};
 const prepare=()=>run('prepare',async()=>{const data=await api<Preparation>(`/shifts/${selected}/prepare`,{mode});setResult(data);await reload();if(data.invitation)openReview(data.invitation);});
 const approve=()=>run('approve',async()=>{if(!review)return;await api(`/invitations/${review.id}/approve`,{message});setReview(null);setResult(null);setNotice('Invitation approved. Open the volunteer response link below to try accepting or declining.');await reload();});
 const copyLink=async(invitation:Invitation)=>{try{await navigator.clipboard.writeText(`${location.origin}/invite/${invitation.token}`);setNotice(workspace?.hosted?'Volunteer response link copied. Anyone with this link can respond to this invitation.':'Volunteer response link copied. It works on this computer while the local server is running.');}catch{setError('Clipboard access is unavailable. Open the response page and copy its address.');}};
 if(needsLogin)return <main className="login-page"><form className="login-card" onSubmit={e=>{e.preventDefault();void run('login',async()=>{await api('/session',{access_code:accessCode});await reload();setAccessCode('');setNeedsLogin(false);});}}><span className="wordmark">kind</span><h1>A little coordination.<br/>A lot of good.</h1><p>Open your coordinator workspace to keep your community covered.</p><label htmlFor="access-code">Coordinator access code</label><input id="access-code" type="password" autoComplete="current-password" autoFocus value={accessCode} onChange={e=>setAccessCode(e.target.value)} required maxLength={256}/>{error&&<p className="error" role="alert">{error}</p>}<button className="primary wide" disabled={!!busy}>{busy==='login'?'Opening workspace…':'Open workspace'}</button><p className="small-muted">Hackathon demo with fictional records. Volunteer response links open separately.</p></form></main>;
 if(!workspace)return <main className="loading"><span className="wordmark">kind</span><h1>Getting your community ready…</h1>{error?<p className="error" role="alert">{error}</p>:<p>Opening the sample workspace.</p>}</main>;
 const shift=workspace.shifts.find(s=>s.id===selected)??workspace.shifts[0];
 const shiftInvitations=workspace.invitations.filter(i=>i.shift_id===shift.id),activeInvitation=shiftInvitations.find(i=>i.status==='draft');
 const candidate=candidates?.eligible[0], nameOf=(id:string)=>workspace.volunteers.find(v=>v.id===id)?.name??'Volunteer';
 const statusOf=(s:Shift)=>s.assigned.length>=s.required?'covered':workspace.invitations.some(i=>i.shift_id===s.id&&i.status==='pending')?'awaiting':'open';
 const openCount=workspace.shifts.filter(s=>s.assigned.length<s.required).length;
 return <div className="app-shell"><aside className="sidebar"><a href="/" className="wordmark">kind</a><nav aria-label="Main navigation">{([{id:'coverage',label:'Coverage',Icon:CalendarDays},{id:'volunteers',label:'Volunteers',Icon:Users},{id:'activity',label:'Activity',Icon:ClipboardList}] as const).map(({id,label,Icon})=><button key={id} className={view===id?'nav-item selected':'nav-item'} aria-current={view===id?'page':undefined} onClick={()=>setView(id)}><Icon size={21}/>{label}</button>)}</nav><div className="workspace-label"><Building2 size={22}/><div><span>Sample workspace</span><strong>{workspace.organization}</strong></div></div></aside>
 <main className="main-content"><header className="page-header"><div><h1>{view==='coverage'?'Every shift matters.':view==='volunteers'?'Good people. Real impact.':'The little things, handled.'}</h1><p>{view==='coverage'?'Keep your community covered.':view==='volunteers'?'Find the right help, and respect everyone’s time.':'A clear record of every decision and response.'}</p></div><span className="sample-label">Sample data</span></header>
 {error&&<div role="alert" className="error">{error}<button className="text-button" onClick={()=>setError('')}>Dismiss</button></div>}{notice&&<div role="status" className="notice">{notice}<button className="text-button" onClick={()=>setNotice('')}>Dismiss</button></div>}
 {view==='coverage'?<><section className="metrics" aria-label="Coverage summary"><div><strong>{openCount}</strong><span>Open shifts</span></div><div><strong>{workspace.volunteers.length}</strong><span>Volunteers</span></div><div><strong>{workspace.invitations.filter(i=>i.status==='pending').length}</strong><span>Awaiting reply</span></div></section>
 <div className="coverage-layout"><div className="shift-column"><section><div className="section-head"><h2>Upcoming shifts</h2><button className="text-button" disabled={!!busy} onClick={()=>void run('scan',async()=>{const scan=await api<{open_shifts:number}>('/scan',{});await reload();setNotice(`Coverage checked. ${scan.open_shifts} shift(s) need help.`);})}><RefreshCw size={15} className={busy==='scan'?'spin':''}/>Check coverage</button></div><div className="shift-list">{workspace.shifts.map(s=><button key={s.id} className={`shift-row ${selected===s.id?'active':''}`} onClick={()=>choose(s.id)} aria-pressed={selected===s.id}><span className="date-block"><span>{dateLabel(s.start,{month:'short'})}</span><strong>{dateLabel(s.start,{day:'numeric'})}</strong></span><span className="shift-name"><strong>{s.title}</strong><span>{timeRange(s.start,s.end)}</span></span><span className="staff-count">{s.assigned.length} of {s.required}<span> volunteers</span></span><Status status={statusOf(s)}/><ChevronRight size={18}/></button>)}</div></section>
 <section className="details-panel"><h3>Shift details</h3><ShiftDetails shift={shift}/><div className="roster"><strong>On the team</strong>{shift.assigned.length?shift.assigned.map(id=><div className="roster-person" key={id}><Avatar name={nameOf(id)} small/><span>{nameOf(id)}</span><button className="text-button muted" onClick={()=>setCancel({shift,id,name:nameOf(id)})} aria-label={`Record cancellation for ${nameOf(id)}`}><UserMinus size={15}/>Record cancellation</button></div>):<p className="muted">No volunteers assigned yet.</p>}</div></section>
 {shiftInvitations.length>0&&<section className="invitations-section"><div className="section-head"><h2>Invitations</h2></div>{shiftInvitations.map(inv=><div className="invitation-row" key={inv.id}><Avatar name={nameOf(inv.volunteer_id)} small/><div><strong>{nameOf(inv.volunteer_id)}</strong><span className="small-muted">{inv.source==='bedrock'?'Prepared with Strands':'Rules-based workflow'}</span></div><Status status={inv.status}/>{inv.status==='draft'?<button className="text-button" onClick={()=>openReview(inv)}>Review<ArrowRight size={15}/></button>:inv.status==='pending'?<div className="invite-actions"><a href={`/invite/${inv.token}`} rel="noreferrer" className="text-button">Response page<ExternalLink size={14}/></a><button className="icon-button" onClick={()=>void copyLink(inv)} aria-label={`Copy invitation link for ${nameOf(inv.volunteer_id)}`}><Copy size={15}/></button></div>:null}{['draft','pending'].includes(inv.status)&&<button className="text-button muted" disabled={!!busy} onClick={()=>void run('cancel-invite',async()=>{await api(`/invitations/${inv.id}/cancel`,{});await reload();})}>Cancel</button>}</div>)}</section>}
 <section className="latest-activity"><div className="section-head"><h2>Latest activity</h2><button className="text-button" onClick={()=>setView('activity')}>View all activity<ArrowRight size={17}/></button></div><ActivityList items={workspace.activity.slice(0,3)}/></section></div>
 <aside className="recommendation"><h2>A little help from Kind</h2><p className="panel-intro">{statusOf(shift)==='covered'?'This shift has the help it needs. Thank you.':`${shift.required-shift.assigned.length===1?'One more volunteer is':`${shift.required-shift.assigned.length} more volunteers are`} needed for this shift.`}</p>
 {statusOf(shift)==='covered'?<div className="covered-state"><span><Heart size={34}/></span><h3>Your community is covered.</h3><p>The roster is saved. Kind will notice if coverage changes.</p></div>:<><div className="recommendation-person"><h3>{activeInvitation?'Ready for your review':candidate?'Recommended volunteer':'Replacement availability'}</h3>{activeInvitation||candidate?<div className="person"><Avatar name={activeInvitation?nameOf(activeInvitation.volunteer_id):candidate!.name}/><div><strong>{activeInvitation?nameOf(activeInvitation.volunteer_id):candidate!.name}</strong><span>{candidate&&!activeInvitation?`${candidate.contacts} invitations in the last 7 days`:'Draft invitation prepared'}</span></div></div>:<p className="muted">{candidates?'No eligible replacements remain. Review the exclusions below or talk with your team.':'Checking availability…'}</p>}</div>
 {(candidate||activeInvitation)&&<div className="eligibility"><h3>Eligible for this shift</h3><p><Check/>Available for the full shift</p><p><Check/>{shift.qualification} qualified</p><p><Check/>No overlapping commitments</p><p><Check/>Within the weekly contact limit</p></div>}
 <label className="mode-label" htmlFor="agent-mode">Prepare with</label><select id="agent-mode" value={mode} onChange={e=>setMode(e.target.value as 'rules'|'bedrock')}><option value="rules">Rules mode · no AI calls</option><option value="bedrock">Strands + Amazon Bedrock</option></select>{mode==='bedrock'&&!workspace.bedrock_configured&&<p className="small-muted">Live mode needs AWS access configured for this app.</p>}
 <button className="primary wide" disabled={!!busy||(!activeInvitation&&!candidate)} onClick={()=>activeInvitation?openReview(activeInvitation):void prepare()}>{busy==='prepare'?'Preparing invitation…':activeInvitation?'Review invitation':'Prepare invitation'}</button>
 <button className="secondary wide" disabled={!!busy} onClick={()=>void run('find',async()=>{setCandidates(await api<Candidates>(`/shifts/${selected}/candidates`));setNotice('Eligibility refreshed. Candidates with fewer recent invitations are considered first.');})}>Find replacements</button>
 {result&&<p className="agent-summary">{result.summary}</p>}
 {candidates&&<details className="exclusions"><summary>{candidates.excluded.length} volunteers not available</summary>{candidates.excluded.map(v=><p key={v.id}><strong>{v.name}</strong>{v.reasons.join(' · ')}</p>)}</details>}</>}
 <ApprovalNote/><p className="local-disclosure">Fictional records. Approval creates an in-app response link; no email or text is sent.</p></aside></div></>:view==='volunteers'?<><div className="directory-toolbar"><h2>Volunteer directory <span className="count">{workspace.volunteers.length}</span></h2><label className="search"><Search size={18}/><input aria-label="Search volunteers" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a volunteer"/></label></div><div className="volunteer-table"><div className="table-head"><span>Volunteer</span><span>Qualifications</span><span>Invitations</span><span>Current assignments</span></div>{workspace.volunteers.filter(v=>v.name.toLowerCase().includes(search.toLowerCase())).map(v=><div className="volunteer-row" key={v.id}><div className="person"><Avatar name={v.name}/><strong>{v.name}</strong></div><span>{v.qualifications.join(' · ')}</span><span className={v.opted_in?'opted-in':'muted'}>{v.opted_in?'Accepting invitations':'Opted out'}</span><span>{workspace.shifts.filter(s=>s.assigned.includes(v.id)).length} shifts</span></div>)}{workspace.volunteers.filter(v=>v.name.toLowerCase().includes(search.toLowerCase())).length===0&&<p className="empty">No volunteers match “{search}”.</p>}</div><div className="directory-note"><ShieldCheck/><p>Kind checks availability, required qualifications, existing commitments and contact limits before preparing an invitation. All records in this workspace are fictional.</p></div></>:<><div className="section-head"><h2>Workspace activity</h2><span className="small-muted">Saved across sessions</span></div><ActivityList items={workspace.activity}/>{workspace.agent_runs.length>0&&<section className="run-history"><h2>Preparation history</h2>{workspace.agent_runs.map(run=><details key={run.id}><summary>{run.source==='bedrock'?'Strands + Bedrock':'Rules mode'} · {workspace.shifts.find(s=>s.id===run.shift_id)?.title}</summary><p>{run.result}</p><ol>{run.trace.map((t,i)=><li key={i}><strong>{t.tool}</strong> — {t.detail}</li>)}</ol></details>)}</section>}</>}
 <footer className="app-footer"><span>Kind · A little coordination. A lot of good.</span><span>{workspace.hosted?'Hosted':'Local'} sample workspace · Times in Pacific</span><button className="text-button" disabled={!!busy} onClick={()=>setRestartSample(true)}>Restart sample</button>{workspace.hosted&&<button className="text-button" onClick={()=>void run('logout',async()=>{await api('/logout',{});setWorkspace(null);setNeedsLogin(true);})}>Sign out</button>}</footer>
 </main>
 {restartSample&&<Dialog title="Restart the sample workspace?" onClose={()=>{if(!busy)setRestartSample(false);}}><p>This replaces the shared fictional roster, invitations and activity with fresh future shifts. Existing sample response links will stop working. The daily AI allowance stays the same.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="button-row"><button className="primary" disabled={!!busy} onClick={()=>void run('restart',async()=>{await api('/sample/restart',{confirm:'restart fictional sample'});setRestartSample(false);setReview(null);setCancel(null);setResult(null);setSelected('s1');setView('coverage');await reload();setNotice('Fresh sample shifts are ready. No model call was made.');})}>Restart fictional sample</button><button className="secondary" disabled={!!busy} onClick={()=>setRestartSample(false)}>Keep current workspace</button></div></Dialog>}
 {review&&<Dialog title="Review invitation" onClose={()=>{if(!busy)setReview(null);}}><div className="review-person"><Avatar name={nameOf(review.volunteer_id)}/><div><strong>{nameOf(review.volunteer_id)}</strong><p className="muted">{workspace.shifts.find(s=>s.id===review.shift_id)?.title}</p></div></div><label htmlFor="invitation-message">Your invitation</label><textarea id="invitation-message" rows={8} maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)}/><p className="small-muted">Approval creates a response link for this volunteer. No email or text message will be sent.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="button-row"><button className="primary" disabled={!!busy||!message.trim()} onClick={()=>void approve()}>{busy==='approve'?'Approving…':'Approve invitation'}</button><button className="secondary" disabled={!!busy} onClick={()=>setReview(null)}>Keep as draft</button></div><ApprovalNote/></Dialog>}
 {cancel&&<Dialog title="Record a cancellation" onClose={()=>setCancel(null)}><p>Remove <strong>{cancel.name}</strong> from <strong>{cancel.shift.title}</strong>? Kind will flag the staffing gap and help you find a replacement.</p><div className="button-row"><button className="primary" disabled={!!busy} onClick={()=>void run('cancellation',async()=>{await api(`/shifts/${cancel.shift.id}/cancel-assignment`,{volunteer_id:cancel.id});setCancel(null);await reload();})}>Record cancellation</button><button className="secondary" disabled={!!busy} onClick={()=>setCancel(null)}>Keep assignment</button></div></Dialog>}
 </div>;
}
